CREATE TABLE TB_RP_M_USR
(
ID							NUMBER(38, 0) NOT NULL,
NAME						NVARCHAR2(30),
EMAIL						VARCHAR2(2000) 	,
ABOUT     					NVARCHAR2(50),
CNTCT_NUMBER				VARCHAR2(50)
);						
ALTER TABLE TB_RP_M_USR ADD CONSTRAINT M_USR_PK PRIMARY KEY(ID); 