CREATE TABLE TB_RP_M_RATING
(
ID								NUMBER(38, 0) NOT NULL,
USER_ID							NUMBER(38,0) NOT NULL,
HOTEL_ID						NUMBER(38,0)NOT NULL ,
RATINGS     					NUMBER(38,0),
FEEDBACK						NVARCHAR2(2000)
);						
ALTER TABLE TB_RP_M_RATING ADD CONSTRAINT M_RATING_PK PRIMARY KEY(ID); 